{{- if not .Values.keycloak.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ required "keycloak.auth.adminPassword is required when not using existingSecret" .Values.keycloak.auth.adminPassword | b64enc | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ required "database.password is required when not using database.existingSecret" .Values.database.password | b64enc | quote }}
{{- end }}
