{{- range $name, $values := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keda.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "keda.labels" $ | nindent 4 }}
  {{- with $values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" $values.type }}
{{- with $values.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $values.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
